   adrez_poc:
     outputs:
       dev:
         type: sqlserver
         driver: 'ODBC Driver 18 for SQL Server'
         server: adrez-poc-sqldb-server.database.windows.net
         database: adrez-poc-sqldb
         schema: adrez_poc
         authentication: sql
         user: martin.krecek
         password: "{{ env_var('DBT_PASSWORD') }}"
         port: 1433
         trust_cert: true
         encrypt: true
     target: dev
